# DigitalOcean App Platform Configuration
name: eduscan
region: fra
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/EduScan
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: "production"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_APPWRITE_ENDPOINT
        value: "${NEXT_PUBLIC_APPWRITE_ENDPOINT}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_PROJECT_ID
        value: "${NEXT_PUBLIC_APPWRITE_PROJECT_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: APPWRITE_API_KEY
        value: "${APPWRITE_API_KEY}"
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_APPWRITE_DATABASE_ID
        value: "${NEXT_PUBLIC_APPWRITE_DATABASE_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_ATTENDANCE_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_ATTENDANCE_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_ORGANIZATIONS_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_ORGANIZATIONS_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_SESSIONS_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_SESSIONS_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_DEPARTMENTS_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_DEPARTMENTS_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_APPWRITE_COURSES_COLLECTION_ID
        value: "${NEXT_PUBLIC_APPWRITE_COURSES_COLLECTION_ID}"
        scope: RUN_AND_BUILD_TIME
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
        scope: RUN_TIME
        type: SECRET
      - key: FREE_TRIAL_DAYS
        value: "24"
        scope: RUN_TIME
